# wrangler.toml
name = 'laddressa-ai'
compatibility_date = "2024-01-01"

# This is for Cloudflare Pages deployment
pages_build_output_dir = "apps/web/out"

[env.production]
vars = { NODE_ENV = "production" }