name = "laddressa-api"
main = "api-worker.js"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "laddressa-db"
database_id = "your-database-id"
