name = "laddrressa-ai"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[pages_build_output_dir]]
value = "apps/web/.next"

[env.production.vars]
NODE_ENV = "production"